server:
  port: 8081

---

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_atmmm
    username: root
    password: 3128


  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: on 
